server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-compra-service
          uri: lb://ms-compra-service
          predicates:
            - Path=/compras/**

        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/categorias/**
